# Generated by Django 5.1 on 2024-08-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BiologicalModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeneticSourceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('impact_factor', models.FloatField(blank=True, null=True)),
                ('pmid', models.CharField(blank=True, max_length=50, null=True)),
                ('funding_source', models.CharField(blank=True, max_length=1000, null=True)),
                ('lead_author', models.CharField(blank=True, max_length=100, null=True)),
                ('phenotype', models.TextField(blank=True, null=True)),
                ('diagnostic_criteria_used', models.TextField(blank=True, null=True)),
                ('sample_size', models.CharField(blank=True, max_length=255, null=True)),
                ('age_range', models.CharField(blank=True, max_length=255, null=True)),
                ('mean_age', models.CharField(blank=True, max_length=255, null=True)),
                ('male_female_split', models.CharField(blank=True, max_length=250, null=True)),
                ('biological_risk_factor_studied', models.TextField(blank=True, null=True)),
                ('biological_rationale_provided', models.TextField(blank=True, null=True)),
                ('status_of_corresponding_gene', models.TextField(blank=True, null=True)),
                ('technology_platform', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation_method', models.CharField(blank=True, max_length=1000, null=True)),
                ('statistical_model', models.CharField(blank=True, max_length=255, null=True)),
                ('criteria_for_significance', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_performed', models.CharField(blank=True, max_length=255, null=True)),
                ('findings_conclusions', models.TextField(blank=True, null=True)),
                ('generalisability_of_conclusion', models.CharField(blank=True, max_length=255, null=True)),
                ('adequate_statistical_powered', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation_method_statistical_model', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('should_exclude', models.BooleanField(default=False)),
                ('article_type', models.ManyToManyField(blank=True, null=True, to='ResearchApp.articletype')),
                ('biological_modalities', models.ManyToManyField(blank=True, null=True, to='ResearchApp.biologicalmodality')),
                ('disorder', models.ManyToManyField(blank=True, null=True, to='ResearchApp.disorder')),
                ('genetic_source_materials', models.ManyToManyField(blank=True, null=True, to='ResearchApp.geneticsourcematerial')),
                ('research_regions', models.ManyToManyField(blank=True, null=True, to='ResearchApp.researchregion')),
                ('study_designs', models.ManyToManyField(blank=True, null=True, to='ResearchApp.studydesign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title', 'year', 'pmid'), name='unique_study')],
            },
        ),
    ]
