# Generated by Django 5.1 on 2024-08-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='study',
            name='biological_modalities',
        ),
        migrations.RemoveField(
            model_name='study',
            name='disorder',
        ),
        migrations.RemoveField(
            model_name='study',
            name='genetic_source_materials',
        ),
        migrations.RemoveField(
            model_name='study',
            name='research_regions',
        ),
        migrations.RemoveField(
            model_name='study',
            name='study_designs',
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
        migrations.DeleteModel(
            name='BiologicalModality',
        ),
        migrations.DeleteModel(
            name='Disorder',
        ),
        migrations.DeleteModel(
            name='GeneticSourceMaterial',
        ),
        migrations.DeleteModel(
            name='ResearchRegion',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.DeleteModel(
            name='StudyDesign',
        ),
    ]
