# Generated by Django 5.1 on 2024-08-16 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchApp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletype',
            old_name='name',
            new_name='article_name',
        ),
        migrations.RenameField(
            model_name='disorder',
            old_name='name',
            new_name='disorder_name',
        ),
        migrations.RemoveField(
            model_name='study',
            name='study_designs',
        ),
        migrations.AlterField(
            model_name='studydesign',
            name='design_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='study',
            name='study_designs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ResearchApp.studydesign'),
        ),
    ]
