# Generated by Django 5.1 on 2024-08-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchApp', '0004_rename_name_articletype_article_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_designs',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.DeleteModel(
            name='StudyDesign',
        ),
    ]
