# Generated by Django 5.1 on 2024-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchApp', '0006_studydesign_alter_study_study_designs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='study',
            name='evaluation_method_statistical_model',
        ),
        migrations.AddField(
            model_name='study',
            name='author_regions',
            field=models.ManyToManyField(blank=True, null=True, to='ResearchApp.authorregion'),
        ),
    ]
