# Generated by Django 5.1 on 2024-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchApp', '0007_authorregion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorRegion',
            new_name='Country',
        ),
        migrations.RemoveField(
            model_name='study',
            name='research_regions',
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'Study', 'verbose_name_plural': 'Studies'},
        ),
        migrations.RemoveField(
            model_name='study',
            name='author_regions',
        ),
        migrations.AddField(
            model_name='study',
            name='DOI',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='study',
            name='abstract',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='affiliations',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='authors',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='automatic_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='citation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='countries',
            field=models.ManyToManyField(blank=True, to='ResearchApp.country'),
        ),
        migrations.AddField(
            model_name='study',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='pages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='article_type',
            field=models.ManyToManyField(blank=True, to='ResearchApp.articletype'),
        ),
        migrations.AlterField(
            model_name='study',
            name='biological_modalities',
            field=models.ManyToManyField(blank=True, to='ResearchApp.biologicalmodality'),
        ),
        migrations.AlterField(
            model_name='study',
            name='disorder',
            field=models.ManyToManyField(blank=True, to='ResearchApp.disorder'),
        ),
        migrations.AlterField(
            model_name='study',
            name='genetic_source_materials',
            field=models.ManyToManyField(blank=True, to='ResearchApp.geneticsourcematerial'),
        ),
        migrations.DeleteModel(
            name='ResearchRegion',
        ),
    ]
