# Generated by Django 5.1 on 2024-09-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchApp', '0008_rename_authorregion_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='affiliations',
            new_name='authors_affiliations',
        ),
        migrations.RemoveField(
            model_name='study',
            name='authors',
        ),
        migrations.AddField(
            model_name='study',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
