# Generated by Django 5.1 on 2024-09-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchApp', '0009_rename_affiliations_study_authors_affiliations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='study',
            name='automatic_tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='male_female_split',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='volume',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
