# Generated by Django 5.1 on 2024-09-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchApp', '0010_alter_country_name_alter_study_automatic_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='automatic_tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='criteria_for_significance',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='generalisability_of_conclusion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='issue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='statistical_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='technology_platform',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='validation_performed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
