# Generated by Django 5.1.1 on 2025-05-24 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchApp', '0013_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studies', models.ManyToManyField(related_name='saved_responses', to='ResearchApp.study')),
            ],
        ),
        migrations.CreateModel(
            name='StudyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='ResearchApp.study')),
            ],
        ),
        migrations.CreateModel(
            name='StudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='study_images/')),
                ('caption', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ResearchApp.study')),
            ],
        ),
    ]
