# Generated by Django 5.1 on 2024-09-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='about_page',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='section',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission_content',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='technology_content',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='technology_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='vision_content',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='vision_title',
        ),
        migrations.AddField(
            model_name='objective',
            name='about_page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='Aboutpage.aboutpage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='About PsychGen-Africa', max_length=255),
        ),
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='Aboutpage.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=255)),
                ('content', models.TextField()),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='Aboutpage.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Technology and Development', max_length=255)),
                ('content', models.TextField()),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='Aboutpage.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Vision', max_length=255)),
                ('content', models.TextField()),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision', to='Aboutpage.aboutpage')),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
